# Generated by Django 4.2.13 on 2024-06-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0003_alter_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='isactive',
            field=models.BooleanField(null=True, verbose_name='Sayfayı Göster'),
        ),
        migrations.AddField(
            model_name='blog',
            name='subtitle',
            field=models.CharField(blank=True, default='Alt başlık yoktur', max_length=50, verbose_name='Alt Başlık'),
        ),
    ]
