# Generated by Django 4.2.13 on 2024-06-05 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0007_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
