# Generated by Django 4.2.13 on 2024-06-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0010_comment_blog_alter_comment_date_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Kategori Başlığı')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
        ),
    ]
